development:
  adapter: postgresql
  encoding: unicode
  database: dayjob_dev
  pool: 5
  username: dayjob
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: dayjob_test
  pool: 5
  username: dayjob
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: dayjob_prod
  pool: 5
  username: dayjob
  password:
  host: localhost
  port: 5432
